### ISSUE TITLE
User Story #3: Implement Backend Logic for Emoji Reactions

### ISSUE THREAD

**Issue by T7alabdullah** [CMU-17313Q/nodebb-f24-team-pawsitive#11]
**Description:**

- Implement backend functionality to associate emoji reactions with answers.
- Manage addition, removal, and persistence of emoji reactions in the database.

**Estimated Effort:** Medium

**Acceptance Criteria:**

- Emoji reactions are properly stored in the database.
- Users can add and remove reactions to answers.

**Comment by mthani2** [comment]
Backend logic has been implemented and is evidenced in the emoji-reaction-branch.
