### ISSUE TITLE
User Story 2: Testing Full Solved Button Feature

### ISSUE THREAD

**Issue by Nalseaf** [CMU-17313Q/nodebb-f24-team-pawsitive#9]
**Description:** Ensure the "mark as solved" feature works correctly from backend to frontend, and that unit tests cover the core functionality.

**Estimated Effort:** Medium

**Dependencies:** Backend and frontend tasks must be completed.
**Acceptance Criteria:**

1. Original poster can successfully mark/unmark questions as "solved."
2. "Solved" questions are visually distinguished from unsolved ones.
3. Tests verify that the feature works end-to-end.

**Comment by mthani2** [comment]
This issue is half completed as the frontend changes have been testing manually and are proven completed by the team #28 .
The issue does not include any automated tests yet due to issues with the backend implementation, documented in the PR #29.
